export const RECEIVE_ROOMDETAIL = 'RECEIVE_ROOMDETAIL'
export const RECEIVE_ROOMALLHOTLIST = 'RECEIVE_ROOMALLHOTLIST'
export const RECEIVE_ROOMLONGPOLING = 'RECEIVE_ROOMLONGPOLING'
export const RECEIVE_ROOMDETAILSUCCESS = 'RECEIVE_ROOMDETAILSUCCESS'
export const RECEIVE_ROOMID = 'RECEIVE_ROOMID'

export const RECEIVE_ISLOGIN = 'RECEIVE_ISLOGIN'
export const RECEIVE_USERINFO = 'RECEIVE_INFO'
export const RECEIVE_USERSIG = 'RECEIVE_USERSIG'

export const RECEIVE_ROOMPRAISE = 'RECEIVE_ROOMPRAISE'
export const RECEIVE_ROOMTOP = 'RECEIVE_ROOMTOP'

export const RECEIVE_WEBIMDATA = 'RECEIVE_WEBIMDATA'
export const ADD_WEBIMDATA = 'ADD_WEBIMDATA'
export const REMOVE_WEBIMDATA = 'REMOVE_WEBIMDATA'
export const RECEIVE_WEBIMOBJ = 'RECEIVE_WEBIMOBJ'
export const RECEIVE_WEBIMPACKMSG = 'RECEIVE_WEBIMPACKMSG'
export const RECEIVE_WEBIMJOINSTATUS = 'RECEIVE_WEBIMJOINSTATUS'
export const RECEIVE_WEBIMBLOCKSTATE = 'RECEIVE_WEBIMBLOCKSTATE'
export const RECEIVE_WEBIM_ISSTOPCMTUSER = 'RECEIVE_WEBIM_ISSTOPCMTUSER'
export const RECEIVE_WEBIM_ISFORBIDUSER = 'RECEIVE_WEBIM_ISFORBIDUSER'
export const RECEIVE_WEBIM_ISALLOWTALK = 'RECEIVE_WEBIM_ISALLOWTALK'
export const RECEIVE_WEBIM_ISROOMCONTROLUSER = 'RECEIVE_WEBIM_ISROOMCONTROLUSER'
export const RECEIVE_WEBIM_GROUPINFO = 'RECEIVE_WEBIM_GROUPINFO'
export const RECEIVE_IMGROUPID = 'RECEIVE_IMGROUPID'

export const RECEIVE_GIFTLIST = 'RECEIVE_GIFTLIST'

export const RECEIVE_HOMEALLHOTLIST = 'RECEIVE_HOMEALLHOTLIST'
export const RECEIVE_VIDEOREC = 'RECEIVE_VIDEOREC'
export const RECEIVE_TAGLIST = 'RECEIVE_TAGLIST'
export const ADD_TAGVIDEOLIST = 'ADD_TAGVIDEOLIST'
export const RECEIVE_CHANNELREC = 'RECEIVE_CHANNELREC'

export const RECEIVE_HEADERTITLE = 'RECEIVE_HEADERTITLE'

export const RESET_LISTDATA = 'RESET_LISTDATA'
export const ADD_DATALIST = 'ADD_DATALIST'
export const RECEIVE_COLUMN = 'RECEIVE_COLUMN'
export const RECEIVE_TAGID = 'RECEIVE_TAGID'
export const RECEIVE_TAGNAME = 'RECEIVE_TAGNAME'

export const RECEIVE_CHANNELDETAIL = 'RECEIVE_CHANNELDETAIL'
export const RECEIVE_STATPOLING = 'RECEIVE_STATPOLING'
export const RECEIVE_ISLOGINIM = 'RECEIVE_ISLOGINIM'

export const RESET_ROOMSTATE = 'RESET_ROOMSTATE'


